name: asard_dev
channels:
  - conda-forge
dependencies:
  - cesard
  - click>=7.1.0
  - gdal>=3.5.0
  - numpy
  - pyrosar>=0.32.0
  - python-dateutil
  - spatialist>=0.15.2
  - sphinx<=6.2.1
  - sphinxcontrib-bibtex>=2.2
  - nbsphinx
  - sphinx_rtd_theme
