name: asard_dev
channels:
  - conda-forge
dependencies:
  - cesard>=1.0.1
  - click>=7.1.0
  - gdal>=3.5.0
  - numpy
  - pyrosar>=0.32.0
  - python-dateutil
  - spatialist>=0.15.2
  - sphinx
  - sphinxcontrib-bibtex>=2.2
  - nbsphinx
  - sphinx_rtd_theme
