name: nrb_env
channels:
  - conda-forge
  - defaults
dependencies:
  - click>=7.1.0
  - gdal>=3.5.0
  - lxml
  - pip
  - pyproj
  - pyroSAR>=0.30.0
  - pystac>=1.8.0,<1.11.0
  - scipy
  - shapely
  - spatialist>=0.15.2